<?php

// Account
const MAIL_ACTIVE_ACCOUNT = 'usr001';
const MAIL_REMAIN_ACCOUNT = 'usr002';

// Status report daily
const MAIL_REPORT_DAILY_TOP_USR_GETLINK = 'rpt001';
const MAIL_REPORT_DAILY_BW_SERVER_USAGE = 'rpt002';

// Notify
const MAIL_NOTIFY_HOST_ACCOUNT_ERROR  = 'noti001';
const MAIL_NOTIFY_USR_UPGRADE_VIP     = 'noti002';
const MAIL_NOTIFY_TRANSACTION_INVALID = 'noti003';
const MAIL_NOTIFY_DELETE_POST         = 'noti004';

// Re-upload
const MAIL_NOTIFY_REUP_UPLOADER_ACCEPT_TO_USER     = 'noti005a';
const MAIL_NOTIFY_REUP_UPLOADER_ACCEPT_TO_UPLOADER = 'noti005b';
const MAIL_NOTIFY_REUP_UPLOADER_SUBMIT_RESULT      = 'noti006';
const MAIL_NOTIFY_REUP_ADMIN_CONFIRM_TO_USER       = 'noti007a';
const MAIL_NOTIFY_REUP_ADMIN_CONFIRM_TO_UPLOADER   = 'noti007b';
const MAIL_NOTIFY_REUP_FAILURE_TO_USER             = 'noti008a';
const MAIL_NOTIFY_REUP_FAILURE_TO_UPLOADER         = 'noti008b';
