<?php

// Account
const MAIL_ACTIVE_ACCOUNT = 'usr001';
const MAIL_REMAIN_ACCOUNT = 'usr002';

// Status report daily
const MAIL_REPORT_DAILY_TOP_USR_GETLINK = 'rpt001';
const MAIL_REPORT_DAILY_BW_SERVER_USAGE = 'rpt002';

// Notify
const MAIL_NOTIFY_HOST_ACCOUNT_ERROR  = 'noti001';
const MAIL_NOTIFY_USR_UPGRADE_VIP     = 'noti002';
const MAIL_NOTIFY_TRANSACTION_INVALID = 'noti003';
const MAIL_NOTIFY_DELETE_POST         = 'noti004';

// Re-upload
const MAIL_NOTIFY_UPLOADER_ACCEPT_REUP_FOR_USER     = 'noti005a';
const MAIL_NOTIFY_UPLOADER_ACCEPT_REUP_FOR_UPLOADER = 'noti005b';
